### ISSUE TITLE
Readme: Explain why sync

### ISSUE THREAD

**Issue by mk-pmb** [shemanaev/node-lpt#6]
Hi, thanks for this module!
Reading the readme, it looks like access is done via getters and setters, in a sync fashion, so I wondered whether that is to be considered blocking I/O. Could you add some explanation to the readme about your timing considerations? Mostly, whether the bindings' actions could cause the CPU to waste time for waiting.

**Comment by shemanaev** [comment]
Hi. This module is a thin middleware between `node` and `parport` driver
and AFAIK `parport`'s ioctl calls shouldn't wait for anything and should
return immediately, so there's no need for async. But i'm not tested it in
all possible modes with any extreme timings.

2017-05-15 23:55 GMT+03:00 M.K. <notifications@github.com>:
